package response

type ResCreateLink struct {
	HubNameExStr                      string `json:"HubName_Ex_str"`
	OnlineBool                        bool   `json:"Online_bool"`
	CheckServerCertBool               bool   `json:"CheckServerCert_bool"`
	ServerCertBin                     string `json:"ServerCert_bin"`
	AccountNameUtf                    string `json:"AccountName_utf"`
	HostnameStr                       string `json:"Hostname_str"`
	PortU32                           int    `json:"Port_u32"`
	ProxyTypeU32                      int    `json:"ProxyType_u32"`
	ProxyNameStr                      string `json:"ProxyName_str"`
	ProxyPortU32                      int    `json:"ProxyPort_u32"`
	ProxyUsernameStr                  string `json:"ProxyUsername_str"`
	ProxyPasswordStr                  string `json:"ProxyPassword_str"`
	HubNameStr                        string `json:"HubName_str"`
	MaxConnectionU32                  int    `json:"MaxConnection_u32"`
	UseEncryptBool                    bool   `json:"UseEncrypt_bool"`
	UseCompressBool                   bool   `json:"UseCompress_bool"`
	HalfConnectionBool                bool   `json:"HalfConnection_bool"`
	AdditionalConnectionIntervalU32   int    `json:"AdditionalConnectionInterval_u32"`
	ConnectionDisconnectSpanU32       int    `json:"ConnectionDisconnectSpan_u32"`
	DisableQoSBool                    bool   `json:"DisableQoS_bool"`
	NoTls1Bool                        bool   `json:"NoTls1_bool"`
	NoUdpAccelerationBool             bool   `json:"NoUdpAcceleration_bool"`
	AuthTypeU32                       int    `json:"AuthType_u32"`
	UsernameStr                       string `json:"Username_str"`
	HashedPasswordBin                 string `json:"HashedPassword_bin"`
	PlainPasswordStr                  string `json:"PlainPassword_str"`
	ClientXBin                        string `json:"ClientX_bin"`
	ClientKBin                        string `json:"ClientK_bin"`
	PolicyDHCPFilterBool              bool   `json:"policy:DHCPFilter_bool"`
	PolicyDHCPNoServerBool            bool   `json:"policy:DHCPNoServer_bool"`
	PolicyDHCPForceBool               bool   `json:"policy:DHCPForce_bool"`
	SecPolCheckMacBool                bool   `json:"SecPol_CheckMac_bool"`
	SecPolCheckIPBool                 bool   `json:"SecPol_CheckIP_bool"`
	PolicyArpDhcpOnlyBool             bool   `json:"policy:ArpDhcpOnly_bool"`
	PolicyPrivacyFilterBool           bool   `json:"policy:PrivacyFilter_bool"`
	PolicyNoServerBool                bool   `json:"policy:NoServer_bool"`
	PolicyNoBroadcastLimiterBool      bool   `json:"policy:NoBroadcastLimiter_bool"`
	PolicyMaxMacU32                   int    `json:"policy:MaxMac_u32"`
	PolicyMaxIPU32                    int    `json:"policy:MaxIP_u32"`
	PolicyMaxUploadU32                int    `json:"policy:MaxUpload_u32"`
	PolicyMaxDownloadU32              int    `json:"policy:MaxDownload_u32"`
	PolicyRSandRAFilterBool           bool   `json:"policy:RSandRAFilter_bool"`
	SecPolRAFilterBool                bool   `json:"SecPol_RAFilter_bool"`
	PolicyDHCPv6FilterBool            bool   `json:"policy:DHCPv6Filter_bool"`
	PolicyDHCPv6NoServerBool          bool   `json:"policy:DHCPv6NoServer_bool"`
	SecPolCheckIPv6Bool               bool   `json:"SecPol_CheckIPv6_bool"`
	PolicyNoServerV6Bool              bool   `json:"policy:NoServerV6_bool"`
	PolicyMaxIPv6U32                  int    `json:"policy:MaxIPv6_u32"`
	PolicyFilterIPv4Bool              bool   `json:"policy:FilterIPv4_bool"`
	PolicyFilterIPv6Bool              bool   `json:"policy:FilterIPv6_bool"`
	PolicyFilterNonIPBool             bool   `json:"policy:FilterNonIP_bool"`
	PolicyNoIPv6DefaultRouterInRABool bool   `json:"policy:NoIPv6DefaultRouterInRA_bool"`
	PolicyVLanIdU32                   int    `json:"policy:VLanId_u32"`
	PolicyVer3Bool                    bool   `json:"policy:Ver3_bool"`
}
